config/routes.rb
Rails.application.routes.draw do
  resources :prospect_characteristics
  resources :prospect_companies
  resources :prospects
  devise_for :users
  get 'pages/home'
  get 'dashboard/index'

  resources :client_companies
  resources :clients
  resources :campaigns
  resources :campaign_results

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :sorted_by,
      :search_query,
      :with_contact_level,
      :with_created_at_gte
    ]
  )

  belongs_to :client_company

  # Scope definitions. We implement all Filterrific filters through ActiveRecord
  # scopes. In this example we omit the implementation of the scopes for brevity.
  # Please see 'Scope patterns' for scope implementation details.
  scope :search_query, lambda { |query|
    # Filters students whose name or email matches the query
    # ...
  }
  scope :sorted_by, lambda { |sort_key|
    # Sorts students by sort_key
    # ...
  }
  scope :with_contact_level, lambda { |contact_level|
    # Filters students with any of the given country_ids
    # ...
  }
  scope :with_created_at_gte, lambda { |ref_date|
    # ...
  }

  # This method provides select options for the `sorted_by` filter select input.
  # It is called in the controller as part of `initialize_filterrific`.
  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'first_name_asc'],
      ['Registration date (newest first)', 'created_at_desc'],
      ['Registration date (oldest first)', 'created_at_asc'],
      ['Contact Level', 'contact_level_asc']
    ]
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  layout "layouts/clients/application"
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index

    @filterrific = initialize_filterrific(
       Client,
       params[:filterrific],
       select_options: {
         sorted_by: Client.options_for_sorted_by,
         # with_contact_level: Client.options_for_select
       },
       persistence_id: 'shared_key',
       default_filter_params: {},
       available_filters: [:sorted_by, :with_contact_level],
     ) or return
     # Get an ActiveRecord::Relation for all students that match the filter settings.
     # You can paginate with will_paginate or kaminari.
     # NOTE: filterrific_find returns an ActiveRecord Relation that can be
     # chained with other scopes to further narrow down the scope of the list,
     # e.g., to apply permissions or to hard coded exclude certain types of records.
     @clients = Client.all
     # Respond to html for initial page load and to js for AJAX filter updates.
     # respond_to do |format|
     #   format.html
     #   format.js
     # end

   # Recover from invalid param sets, e.g., when a filter refers to the
    # database id of a record that doesn’t exist any more.
    # In this case we reset filterrific and discard all filter params.
    rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return


  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:client_company_id, :contact_level, :title, :first_name, :last_name, :email, :phone_number, :mobile_number, :branch_location)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_clients_filter.html.erb
<div class="row">
  <div class="col">
    <p class="lead">
      <%= icon ("sliders"), style: "margin-right: 10px;" %>
      Filters <span class="small">(placeholder)</span>
    </p>
  </div>
  <div class="col text-right">

    <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="true" aria-controls="collapseExample">
      <%= icon ("bars") %>
    </button>

  </div>
</div>

<div class="collapse show" id="collapseExample">
  <div class="row" style="margin-bottom: 35px; margin-top: 25px;">
    <div class="col ">

      <form class="form-inline justify-content-center">
        <input class="form-control col-7" type="search" placeholder="Quick Search" aria-label="Search">
        <button class="btn btn-outline-primary col-3" type="submit" style="margin-left: 10px;">Search</button>
      </form>

    </div>

  </div>
  <div style="padding-bottom: 20px; border-top: 1px solid #c7ced5">

  </div>
  <div class="row">

    <div class="col">
      <label for="example-date-input">Status</label>
      <select class="custom-select">
        <option selected>Active</option>
        <option value="1">Inactive</option>
        <option value="2">On Hold</option>
      </select>

    </div>
    <div class="col">
      <label for="example-date-input">Type</label>
      <select class="custom-select">
        <option selected>VC/PE</option>
        <option value="1">Weath Manager/IFA</option>
        <option value="2">Start Up</option>
        <option value="3">Recruiter</option>
        <option value="3">Education</option>
      </select>

    </div>
    <div class="col">

      <div class="form-group">
        <label for="example-date-input">Created</label>
        <div>
          <input class="form-control" type="date" value="2011-08-19" id="example-date-input">
        </div>
      </div>

    </div>
    <div class="col">

      <div class="form-group">
        <label for="example-date-input">Last Updated</label>
        <div>
          <input class="form-control" type="date" value="2011-08-19" id="example-date-input">
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
    <div class="col">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
          Default checkbox
        </label>
      </div>
    </div>
  </div>
</div>

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-6">
        <div style="padding-bottom: 30px;">
          <p class="lead">
            Create a new company before linking client.
          </p>
            <%= link_to 'New Company', new_client_company_path, class: "btn btn-outline-info", style: "width: 180px;" %>
        </div>

        <%= f.association :client_company, label: 'Link Client to a Company', :label_method => lambda { |client_company| "#{client_company.company_name}" } %>
        <%= f.input :title %>
        <%= f.input :contact_level %>
        <%= f.input :branch_location %>
      </div>
      <div class="col-6">
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :email %>
        <%= f.input :phone_number %>
        <%= f.input :mobile_number %>
      </div>
    </div>
  </div>

  <div class="form-actions text-center">
    <%= f.button :submit, "Save", class: "btn-outline-success", style: "width: 280px; margin: 30px;" %>
  </div>
<% end %>

app/views/clients/_list.html.erb
<%# app/views/students/_list.html.erb %>
<div id="filterrific_results">



  <table class="table table-hover table-responsive-md" cellspacing="0" width="100%">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Country</th>
      <th>Registered at</th>
    </tr>
    <% clients.each do |client| %>
      <tr>
        <td><%= link_to(client.first_name, client_path(client)) %></td>
        <td><%= client.email %></td>
        <td><%= client.contact_level %></td>
        <td><%= client.created_at %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/clients/_show.html.erb
<div class="row">
  <div class="col">
    <p class="lead">Client Info</p><hr />

    <p>
      <strong>Title:</strong>
      <%= @client.title %>
    </p>

    <p>
      <strong>First name:</strong>
      <%= @client.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @client.last_name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @client.email %>
    </p>

    <p>
      <strong>Phone number:</strong>
      <%= @client.phone_number %>
    </p>

    <p>
      <strong>Mobile number:</strong>
      <%= @client.mobile_number %>
    </p>

    <p>
      <strong>Branch location:</strong>
      <%= @client.branch_location %>
    </p>

  </div>
  <div class="col">
    <p class="lead">Cleint Company Info</p><hr />

    <p>
      <strong>Company Name:</strong>
      <%= @client.client_company.company_name %>
    </p>

    <p>
      <strong>Street:</strong>
      <%= @client.client_company.street_address %>
    </p>

    <p>
      <strong>State:</strong>
      <%= @client.client_company.state %>
    </p>

    <p>
      <strong>Post Code:</strong>
      <%= @client.client_company.postal_code %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @client.client_company.city %>
    </p>

    <p>
      <strong>Ccountry:</strong>
      <%= @client.client_company.country %>
    </p>

    <%= link_to 'Edit Company Info', edit_client_company_path(@client), class: "btn btn-sm btn-outline-secondary", style: "width: 180px;" %>

  </div>
</div>

app/views/clients/_table-1.html.erb
<table class="table table-hover"  cellspacing="0" width="100%">
  <thead>
    <tr>
      <th colspan="2"></th>
      <th>Company</th>
      <th>Title</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Branch location</th>

    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to 'View', client, class: "btn btn-sm btn-outline-primary" %></td>
        <td><span class="badge badge-primary"><%= client.contact_level %></span></td>
        <td><%= client.client_company.company_name %></td>
        <td><%= client.title %></td>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.email %></td>
        <td><%= client.branch_location %></td>

        <!-- <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/_table-2.html.erb
<style>
  table.dataTable thead .sorting:before, table.dataTable thead .sorting:after, table.dataTable thead .sorting_asc:before, table.dataTable thead .sorting_asc:after, table.dataTable thead .sorting_desc:before, table.dataTable thead .sorting_desc:after {
  padding: 5px;
  }
  .dataTables_wrapper .mdb-select {
  border: none;
  float: left;
  }
  .dataTables_wrapper .mdb-select.form-control {
  padding-top: 0;
  margin-top: -1rem;
  margin-left: 0.7rem;
  margin-right: 0.7rem;
  width: 100px;
  }
  .dataTables_length label {
  float: left;
  }
  table.dataTable {
  margin-bottom: 3rem!important;
  }
  div.dataTables_wrapper div.dataTables_info {
  padding-top: 0;
  }
  .test {
    background-color: pink;
  }
</style>

<script>
  $(document).ready(function() {
      $('#clients-table').DataTable();
      $('.dataTables_wrapper').find('label').each(function() {
        $(this).parent().append($(this).children());
      });
      $('select').addClass('mdb-select');
      $('.mdb-select').material_select();
  });
</script>

<table id="clients-table" class="table table-hover table-responsive-md" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th colspan="2"></th>
        <th>Company</th>
        <th>Title</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Branch location</th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= link_to 'View', client, class: "btn btn-sm btn-outline-primary" %></td>
          <td><span class="badge badge-primary"><%= client.contact_level %></span></td>
          <td><%= client.client_company.company_name %></td>
          <td><%= client.title %></td>
          <td><%= client.first_name %></td>
          <td><%= client.last_name %></td>
          <td><%= client.email %></td>
          <td><%= client.branch_location %></td>
          <!-- <td><%= link_to 'Edit', edit_client_path(client) %></td>
          <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/clients/_table-3.html.erb
<%#
  Filterrific adds the `form_for_filterrific` view helper:
  * adds dom id 'filterrific_filter'
  * applies javascript behaviors:
      * AJAX form submission on change
      * AJAX spinner while AJAX request is being processed
  * sets form_for options like :url, :method and input name prefix
%>
<%= form_for_filterrific @filterrific do |f| %>
  <div>
    Search
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div>
    Contact Level

  </div>
  <div>
    Registered after
    <%= f.text_field(:with_created_at_gte, class: 'js-datepicker') %>
  </div>
  <div>
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>
  <div>
    <%= link_to(
      'Reset filters',
      reset_filterrific_url,
    ) %>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
<% end %>

<%= render(
    partial: 'clients/list',
    locals: { clients: @clients }
  ) %>

app/views/clients/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div style="min-width: 100%; background-color: white; margin-left: -15px;">
      <h3 style="padding: 20px;">Edit: <%= @client.first_name %> <%= @client.last_name %> - <%= @client.client_company.company_name %></h3>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render partial: "layouts/shared/flash_messages", flash: flash %>
</div>
<div class="container-fluid">
  <div class="row">
    <%= link_to 'Back', clients_path, class: "btn btn-outline-secondary", style: "width: 180px;" %>
  </div>
</div>

<div class="container-fluid" style="margin-bottom: 80px;">
  <div class="row" style="margin-top: 30px;">
    <div class="col" style="margin-left: -15px;">
      <div class="card" style="padding: 20px; min-width: 100%;">

        <%= render 'form', client: @client %>

      </div>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div style="min-width: 100%; background-color: white; margin-left: -15px;">
      <h3 style="padding: 20px;">All Clients (<%= @clients.count %>)</h3>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render partial: "layouts/shared/flash_messages", flash: flash %>
</div>

<div class="container-fluid">
  <div class="row">
    <%= link_to 'New Client', new_client_path, class: "btn btn-outline-secondary", style: "width: 180px;" %> <%= link_to 'New Company', new_client_company_path, class: "btn btn-outline-secondary", style: "margin-left: 20px; width: 180px;" %><%= link_to 'View All Companies', client_companies_path, class: "btn btn-outline-info", style: "margin-left: 20px; width: 180px;" %>
  </div>
</div>

<div class="container-fluid" style="margin-bottom: 80px;">
  <div class="row" style="margin-top: 30px;">
    <div class="card table-responsive" style="padding: 20px; margin-right: 15px;">
      <%= render "clients_filter", client: @client %>
    </div>
  </div>

  <div class="row" style="margin-top: 30px;">
    <div class="card table-responsive" style="padding: 20px; margin-right: 15px;">
      <%= render "table-3", client: @client %>
    </div>
  </div>
</div>

app/views/clients/index.js.erb
<%# app/views/students/index.js.erb %>
<% js = escape_javascript(
  render(partial: 'students/list', locals: { students: @students })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/clients/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div style="min-width: 100%; background-color: white; margin-left: -15px;">
      <h3 style="padding: 20px;">Create a New Client Record</h3>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render partial: "layouts/shared/flash_messages", flash: flash %>
</div>
<div class="container-fluid">
  <div class="row">
    <%= link_to 'Back', clients_path, class: "btn btn-outline-secondary", style: "width: 180px;" %>
  </div>
</div>

<div class="container-fluid" style="margin-bottom: 80px;">
  <div class="row" style="margin-top: 30px;">
    <div class="col" style="margin-left: -15px;">
      <div class="card" style="padding: 20px; min-width: 100%;">

        <%= render 'form', client: @client %>

      </div>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div style="min-width: 100%; background-color: white; margin-left: -15px;">
      <h3 style="padding: 20px;"><%= @client.first_name %> <%= @client.last_name %> - <%= @client.client_company.company_name %></h3>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render partial: "layouts/shared/flash_messages", flash: flash %>
</div>
<div class="container-fluid">
  <div class="row">
    <%= link_to 'Back', clients_path, class: "btn btn-outline-secondary", style: "width: 180px;" %> <%= link_to 'Edit', edit_client_path(@client), class: "btn btn-outline-primary", style: "width: 180px; margin-left: 20px;" %> <%= link_to 'Delete', client_path(@client), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger", style: "width: 180px; margin-left: 20px;" %>
  </div>
</div>

<div class="container-fluid" style="margin-bottom: 80px;">
  <div class="row" style="margin-top: 30px;">
    <div class="col" style="margin-left: -15px;">
      <div class="card" style="padding: 20px; min-width: 100%;">

        <%= render 'show', client: @client %>

      </div>
    </div>
  </div>
</div>