config/routes.rb
Rails.application.routes.draw do
  resources :prospect_characteristics
  resources :prospect_companies
  resources :prospects
  devise_for :users
  get 'pages/home'
  get 'dashboard/index'

  resources :client_companies
  resources :clients
  resources :campaigns
  resources :campaign_results

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prospect_characteristic.rb
class ProspectCharacteristic < ApplicationRecord
  has_one :prospect
end

app/controllers/prospect_characteristics_controller.rb
class ProspectCharacteristicsController < ApplicationController
  before_action :set_prospect_characteristic, only: [:show, :edit, :update, :destroy]

  # GET /prospect_characteristics
  # GET /prospect_characteristics.json
  def index
    @prospect_characteristics = ProspectCharacteristic.all
  end

  # GET /prospect_characteristics/1
  # GET /prospect_characteristics/1.json
  def show
  end

  # GET /prospect_characteristics/new
  def new
    @prospect_characteristic = ProspectCharacteristic.new
  end

  # GET /prospect_characteristics/1/edit
  def edit
  end

  # POST /prospect_characteristics
  # POST /prospect_characteristics.json
  def create
    @prospect_characteristic = ProspectCharacteristic.new(prospect_characteristic_params)

    respond_to do |format|
      if @prospect_characteristic.save
        format.html { redirect_to @prospect_characteristic, notice: 'Prospect characteristic was successfully created.' }
        format.json { render :show, status: :created, location: @prospect_characteristic }
      else
        format.html { render :new }
        format.json { render json: @prospect_characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospect_characteristics/1
  # PATCH/PUT /prospect_characteristics/1.json
  def update
    respond_to do |format|
      if @prospect_characteristic.update(prospect_characteristic_params)
        format.html { redirect_to @prospect_characteristic, notice: 'Prospect characteristic was successfully updated.' }
        format.json { render :show, status: :ok, location: @prospect_characteristic }
      else
        format.html { render :edit }
        format.json { render json: @prospect_characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospect_characteristics/1
  # DELETE /prospect_characteristics/1.json
  def destroy
    @prospect_characteristic.destroy
    respond_to do |format|
      format.html { redirect_to prospect_characteristics_url, notice: 'Prospect characteristic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect_characteristic
      @prospect_characteristic = ProspectCharacteristic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_characteristic_params
      params.require(:prospect_characteristic).permit(:job_title, :seniority_level, :function, :industry, :company_name, :company_headcount, :past_company, :company_type, :school, :language, :years_in_current_position, :years_at_current_company, :years_of_experience)
    end
end

app/helpers/prospect_characteristics_helper.rb
module ProspectCharacteristicsHelper
end

app/views/prospect_characteristics/_form.html.erb
<%= simple_form_for(@prospect_characteristic) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :job_title %>
    <%= f.input :seniority_level %>
    <%= f.input :function %>
    <%= f.input :industry %>
    <%= f.input :company_name %>
    <%= f.input :company_headcount %>
    <%= f.input :past_company %>
    <%= f.input :company_type %>
    <%= f.input :school %>
    <%= f.input :language %>
    <%= f.input :years_in_current_position %>
    <%= f.input :years_at_current_company %>
    <%= f.input :years_of_experience %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/prospect_characteristics/edit.html.erb
<h1>Editing Prospect Characteristic</h1>

<%= render 'form', prospect_characteristic: @prospect_characteristic %>

<%= link_to 'Show', @prospect_characteristic %> |
<%= link_to 'Back', prospect_characteristics_path %>

app/views/prospect_characteristics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prospect Characteristics</h1>

<table>
  <thead>
    <tr>
      <th>Job title</th>
      <th>Seniority level</th>
      <th>Function</th>
      <th>Industry</th>
      <th>Company name</th>
      <th>Company headcount</th>
      <th>Past company</th>
      <th>Company type</th>
      <th>School</th>
      <th>Language</th>
      <th>Years in current position</th>
      <th>Years at current company</th>
      <th>Years of experience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prospect_characteristics.each do |prospect_characteristic| %>
      <tr>
        <td><%= prospect_characteristic.job_title %></td>
        <td><%= prospect_characteristic.seniority_level %></td>
        <td><%= prospect_characteristic.function %></td>
        <td><%= prospect_characteristic.industry %></td>
        <td><%= prospect_characteristic.company_name %></td>
        <td><%= prospect_characteristic.company_headcount %></td>
        <td><%= prospect_characteristic.past_company %></td>
        <td><%= prospect_characteristic.company_type %></td>
        <td><%= prospect_characteristic.school %></td>
        <td><%= prospect_characteristic.language %></td>
        <td><%= prospect_characteristic.years_in_current_position %></td>
        <td><%= prospect_characteristic.years_at_current_company %></td>
        <td><%= prospect_characteristic.years_of_experience %></td>
        <td><%= link_to 'Show', prospect_characteristic %></td>
        <td><%= link_to 'Edit', edit_prospect_characteristic_path(prospect_characteristic) %></td>
        <td><%= link_to 'Destroy', prospect_characteristic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect Characteristic', new_prospect_characteristic_path %>

app/views/prospect_characteristics/new.html.erb
<h1>New Prospect Characteristic</h1>

<%= render 'form', prospect_characteristic: @prospect_characteristic %>

<%= link_to 'Back', prospect_characteristics_path %>

app/views/prospect_characteristics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job title:</strong>
  <%= @prospect_characteristic.job_title %>
</p>

<p>
  <strong>Seniority level:</strong>
  <%= @prospect_characteristic.seniority_level %>
</p>

<p>
  <strong>Function:</strong>
  <%= @prospect_characteristic.function %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @prospect_characteristic.industry %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @prospect_characteristic.company_name %>
</p>

<p>
  <strong>Company headcount:</strong>
  <%= @prospect_characteristic.company_headcount %>
</p>

<p>
  <strong>Past company:</strong>
  <%= @prospect_characteristic.past_company %>
</p>

<p>
  <strong>Company type:</strong>
  <%= @prospect_characteristic.company_type %>
</p>

<p>
  <strong>School:</strong>
  <%= @prospect_characteristic.school %>
</p>

<p>
  <strong>Language:</strong>
  <%= @prospect_characteristic.language %>
</p>

<p>
  <strong>Years in current position:</strong>
  <%= @prospect_characteristic.years_in_current_position %>
</p>

<p>
  <strong>Years at current company:</strong>
  <%= @prospect_characteristic.years_at_current_company %>
</p>

<p>
  <strong>Years of experience:</strong>
  <%= @prospect_characteristic.years_of_experience %>
</p>

<%= link_to 'Edit', edit_prospect_characteristic_path(@prospect_characteristic) %> |
<%= link_to 'Back', prospect_characteristics_path %>