config/routes.rb
Rails.application.routes.draw do
  resources :prospect_characteristics
  resources :prospect_companies
  resources :prospects
  devise_for :users
  get 'pages/home'
  get 'dashboard/index'

  resources :client_companies
  resources :clients
  resources :campaigns
  resources :campaign_results

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client_company.rb
class ClientCompany < ApplicationRecord
  has_many :clients
end

app/controllers/client_companies_controller.rb
class ClientCompaniesController < ApplicationController
  layout "layouts/clients/application"
  before_action :set_client_company, only: [:show, :edit, :update, :destroy]

  # GET /client_companies
  # GET /client_companies.json
  def index
    @client_companies = ClientCompany.all
  end

  # GET /client_companies/1
  # GET /client_companies/1.json
  def show
    @company_clients = Client.where(:client_company_id => @client_company)
  end

  # GET /client_companies/new
  def new
    @client_company = ClientCompany.new
  end

  # GET /client_companies/1/edit
  def edit
  end

  # POST /client_companies
  # POST /client_companies.json
  def create
    @client_company = ClientCompany.new(client_company_params)

    respond_to do |format|
      if @client_company.save
        format.html { redirect_to @client_company, notice: 'Client company was successfully created.' }
        format.json { render :show, status: :created, location: @client_company }
      else
        format.html { render :new }
        format.json { render json: @client_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_companies/1
  # PATCH/PUT /client_companies/1.json
  def update
    respond_to do |format|
      if @client_company.update(client_company_params)
        format.html { redirect_to @client_company, notice: 'Client company was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_company }
      else
        format.html { render :edit }
        format.json { render json: @client_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_companies/1
  # DELETE /client_companies/1.json
  def destroy
    @client_company.destroy
    respond_to do |format|
      format.html { redirect_to client_companies_url, notice: 'Client company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_company
      @client_company = ClientCompany.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_company_params
      params.require(:client_company).permit(:company_name, :street_address, :state, :postal_code, :city, :country)
    end
end

app/helpers/client_companies_helper.rb
module ClientCompaniesHelper
end

app/views/client_companies/_form.html.erb
<%= simple_form_for(@client_company) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company_name %>
    <%= f.input :street_address %>
    <%= f.input :state %>
    <%= f.input :postal_code %>
    <%= f.input :city %>
    <%= f.input :country, selected: [ "United Kingdom" ], collection: [ "Australia", "New Zealand", "United Kingdom" , "United States"] %>
  </div>

  <div class="form-actions text-center">
    <%= f.button :submit, "Save", class: "btn btn-outline-success", style: "margin: 30px; width: 280px;" %>
  </div>
<% end %>

app/views/client_companies/_list_of_clients_for_company.html.erb
<p class="lead">
  Clients Linked to this Company
</p>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="1"></th>
      <th>Title</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Branch location</th>
    </tr>
  </thead>

  <tbody>
    <% @company_clients.each do |client| %>
      <tr>
        <td>
          <%= link_to 'View', client, class: "btn btn-sm btn-outline-primary" %>
        </td>
        <td>
          <%= client.title %>
        </td>
        <td>
          <%= client.first_name %>
        </td>
        <td>
          <%= client.last_name %>
        </td>
        <td>
          <%= client.email %>
        </td>
        <td>
          <%= client.branch_location %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/client_companies/_show.html.erb
<p class="lead">
  Company Details
</p>

<p>
  <strong>Company name:</strong>
  <%= @client_company.company_name %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @client_company.street_address %>
</p>

<p>
  <strong>State:</strong>
  <%= @client_company.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @client_company.postal_code %>
</p>

<p>
  <strong>City:</strong>
  <%= @client_company.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @client_company.country %>
</p>

app/views/client_companies/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div style="min-width: 100%; background-color: white; margin-left: -15px;">
      <h3 style="padding: 20px;">Edit: <%= @client_company.company_name %></h3>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render partial: "layouts/shared/flash_messages", flash: flash %>
</div>
<div class="container-fluid">
  <div class="row">
    <%= link_to 'Back to CRM', clients_path, class: "btn btn-outline-secondary", style: "width: 180px;" %> <%= link_to 'Show Details', client_company_path(@client_company), class: "btn btn-outline-secondary", style: "width: 180px; margin-left: 20px;" %>
  </div>
</div>

<div class="container-fluid" style="margin-bottom: 80px;">
  <div class="row" style="margin-top: 30px;">
    <div class="col" style="margin-left: -15px;">
      <div class="card" style="padding: 20px; min-width: 100%;">

        <%= render 'form', client_company: @client_company %>

      </div>
    </div>
  </div>
</div>

app/views/client_companies/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div style="min-width: 100%; background-color: white; margin-left: -15px;">
      <h3 style="padding: 20px;">All Companies (<%= @client_companies.count %>)</h3>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render partial: "layouts/shared/flash_messages", flash: flash %>
</div>

<div class="container-fluid">
  <div class="row">
    <%= link_to 'New Client', new_client_path, class: "btn btn-outline-secondary", style: "width: 180px;" %> <%= link_to 'New Company', new_client_company_path, class: "btn btn-outline-secondary", style: "margin-left: 20px; width: 180px;" %><%= link_to 'View All Clients', clients_path, class: "btn btn-outline-info", style: "margin-left: 20px; width: 180px;" %>
  </div>
</div>

<div class="container-fluid">
  <div class="row" style="margin-top: 30px;">
    <div class="card table-responsive" style="padding: 20px; margin-right: 15px;">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Company name</th>
            <th>Street address</th>
            <th>State</th>
            <th>Postal code</th>
            <th>City</th>
            <th>Country</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @client_companies.each do |client_company| %>
            <tr>
              <td><%= client_company.company_name %></td>
              <td><%= client_company.street_address %></td>
              <td><%= client_company.state %></td>
              <td><%= client_company.postal_code %></td>
              <td><%= client_company.city %></td>
              <td><%= client_company.country %></td>
              <td><%= link_to 'Show', client_company %></td>
              <td><%= link_to 'Edit', edit_client_company_path(client_company) %></td>
              <td><%= link_to 'Destroy', client_company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/client_companies/new.html.erb
<!-- <%= link_to 'Back', client_companies_path %> -->
<div class="container-fluid">
  <div class="row">
    <div style="min-width: 100%; background-color: white; margin-left: -15px;">
      <h3 style="padding: 20px;">Create a New Company Record</h3>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render partial: "layouts/shared/flash_messages", flash: flash %>
</div>
<div class="container-fluid">
  <div class="row">
    <%= link_to 'Back', clients_path, class: "btn btn-outline-secondary", style: "width: 180px;" %>
  </div>
</div>

<div class="container-fluid" style="margin-bottom: 80px;">
  <div class="row" style="margin-top: 30px;">
    <div class="col" style="margin-left: -15px;">
      <div class="card" style="padding: 20px; min-width: 100%;">

        <%= render 'form', client_company: @client_company %>

      </div>
    </div>
  </div>
</div>

app/views/client_companies/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div style="min-width: 100%; background-color: white; margin-left: -15px;">
      <h3 style="padding: 20px;"><%= @client_company.company_name %></h3>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render partial: "layouts/shared/flash_messages", flash: flash %>
</div>
<div class="container-fluid">
  <div class="row">
    <%= link_to 'Back to CRM', clients_path, class: "btn btn-outline-secondary", style: "width: 180px;" %> <%= link_to 'Edit', edit_client_company_path(@client_company), class: "btn btn-outline-primary", style: "width: 180px; margin-left: 20px;" %> <%= link_to 'Delete', client_company_path(@client_company), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger", style: "width: 180px; margin-left: 20px;" %>
  </div>
</div>

<div class="container-fluid" style="margin-bottom: 80px;">
  <div class="row" style="margin-top: 30px;">
    <div class="col" style="margin-left: -15px;">
      <div class="card" style="padding: 20px; min-width: 100%;">

        <%= render 'show', client: @client_company %>

      </div>
    </div>
  </div>

  <div class="row" style="margin-top: 30px;">
    <div class="col" style="margin-left: -15px;">
      <div class="card" style="padding: 20px; min-width: 100%;">

        <%= render 'list_of_clients_for_company', client: @client_company %>

      </div>
    </div>
  </div>
</div>