config/routes.rb
Rails.application.routes.draw do
  resources :prospect_characteristics
  resources :prospect_companies
  resources :prospects
  devise_for :users
  get 'pages/home'
  get 'dashboard/index'

  resources :client_companies
  resources :clients
  resources :campaigns
  resources :campaign_results

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  belongs_to :client, optional: true
  belongs_to :campaign, optional: true
  belongs_to :prospect_company, optional: true
  belongs_to :prospect_characteristic, optional: true
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  layout "layouts/prospects/application"
  before_action :set_prospect, only: [:show, :edit, :update, :destroy]

  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = Prospect.all
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    @prospect = Prospect.new
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects
  # POST /prospects.json
  def create
    @prospect = Prospect.new(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: 'Prospect was successfully created.' }
        format.json { render :show, status: :created, location: @prospect }
      else
        format.html { render :new }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1
  # PATCH/PUT /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url, notice: 'Prospect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_params
      params.require(:prospect).permit(:client_id, :campaign_id, :prospect_type, :prospect_status, :first_name, :last_name, :email, :phone_number, :mobile_number, :branch_location)
    end
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/layouts/prospects/_header.html.erb
<nav class="navbar navbar-light bg-faded" style="background-color: #5b8da7; height: 60px; colour:white;">
  <div class="container-fluid">
    <div class="col-sm-6">
      <%= image_tag "netz-logo-white.png", class: 'logo' %>
    </div>
    <div class="col-sm-6" style="padding-top: 15px;">
      <ul class="nav justify-content-end" style="padding-bottom:10px;">
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-light btn-sm float-right", style: "width: 90px;" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/prospects/_sidebar.html.erb
<ul class="nav flex-column">
  <li class="nav-item">
    <%= link_to "Dashboard", dashboard_index_path(current_user), class: "nav-link", style: "color:white;" %>
  </li>
  <li class="nav-item">
    <%= link_to "Clients CRM", clients_path(current_user), class: "nav-link", style: "color: white;" %>
  </li>
  <li class="nav-item">
    <%= link_to "Campaigns", campaigns_path(current_user), class: "nav-link", style: "color: white;" %>
  </li>
  <li class="nav-item" style="background-color: #225D7D; margin-right: -15px; border-left: 4px solid white;">
    <%= link_to "Prospect Database", prospects_path(current_user), class: "nav-link", style: "color: white;" %>
  </li>
</ul>

app/views/layouts/prospects/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Netz Database Prototype 01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #f5f6f7;">

    <%= render "layouts/prospects/header" %>

    <div class="row">
      <div class="col-sm-2" style="background-color: #3B718E;">
        <%= render "layouts/prospects/sidebar" %>
      </div>
      <div class="col-sm-10" style="background-color: #f5f6f7; min-height: 700px;">
        <%= yield %>
      </div>
    </div>

  </body>
</html>